### ISSUE TITLE
Get integration tests running distributed index.

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/sync-gateway-testcluster#132]
@ashvindersingh It this already possible? If not, is there anything that need to be done to get this to happen?

**Comment by sethrosetter** [comment]
@ashvindersingh would we have to create distributed index specific configs that the functional tests are consuming to make this happen?

**Comment by ashvindersingh** [comment]
@sethrosetter jenkins job exists http://qa.sc.couchbase.com/view/mobile/job/cen006-p0-mobile-functional-tests-with-sg-cbliteios/
and is configurable to run for 1.2.

**Comment by sethrosetter** [comment]
Closing as dupe of https://github.com/couchbaselabs/sync-gateway-tests/issues/66
