### ISSUE TITLE
Verify bucket online / offline does not cause clients to break

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/sync-gateway-testcluster#136]
Can be a manual test for 1.2.0 per conversation with @zgramana

**Comment by sethrosetter** [comment]
@ashvindersingh I have been manual testing this with Android

**Comment by sethrosetter** [comment]
@borrrden I think this has to be done with .NET as well.

**Comment by borrrden** [comment]
@sethrosetter I thought about this when you said it last night.  Could you elaborate on the way that the client broke?  Was it only when using auth?  I set up a simple integration test last night that will set the sync gateway instance offline during a test and then bring it back a few seconds later and corrected some sluggish behavior I saw there but nothing was actually breaking so far.

**Comment by sethrosetter** [comment]
@borrrden TodoLite Android logged the user out of Facebook auth and then got into a state where it would crash on startup everytime. I have tried to repro today unsuccessfully.

**Comment by sethrosetter** [comment]
Need to be checked on the following

1. Take db offline
2. Take db online
3. Possibly more steps

- [ ]  TodoLite-Android
- [ ]  TodoLite-iOS
- [ ]  SimpleAndroidSync / CouchbaseSample.iOS

**Comment by zgramana** [comment]
@hideki has done this for Java: https://github.com/couchbase/couchbase-lite-java-core/wiki/Couchbase-1.2.0-Test

**Comment by sethrosetter** [comment]
Will be done as part of test fest tomorrow. 

Steps to verify. 
1. All users are pushing shared lists and tasks with some with attachments.
2. GET :4985/db/ make sure status is "Online"
3. While everyone is pushing and pulling, POST :4985/db/_offline
4. All users continue to add lists and tasks, some with attachments. Verify that the clients are operating without error.
5. 2. GET :4985/db/ make sure state is "Offline"
6. POST :4985/db/_resync, make sure successful, perhaps console.log the doc id in the sync function. 
7. After a couple minutes or so, POST :4985/db/_online and make sure that the clients wake up a replicate local offline changes.

**Comment by ajres** [comment]
For step 10, there is no delay option for _offline only _online

**Comment by sethrosetter** [comment]
Found while testing manually during testfest - https://github.com/couchbase/sync_gateway/issues/1527

**Comment by sethrosetter** [comment]
Besides the issue above I tested on Android as part of the release checklist as well as .NET and all seemed to work. @ashvindersingh Can you verify you tested iOS?

**Comment by ashvindersingh** [comment]
@sethrosetter confirming verified with iOS. Found: https://github.com/couchbaselabs/ToDoLite-iOS/issues/61

**Comment by sethrosetter** [comment]
I found this during testing as well - https://github.com/couchbase/couchbase-lite-java-core/issues/963
