### ISSUE TITLE
Run fixed Gateload test with multiple topologies

### ISSUE THREAD

**Issue by zgramana** [couchbaselabs/sync-gateway-testcluster#140]
Run 8 tests where the only variable is the specific index reader / writer ratio. These tests should all use the following test parameters: 5k writers per cluster / 5k readers per cluster / 1KB docs.

EDIT: Hardware specs
3 Couchbase Servers - c3.2xlarge
sync_gateway - c3.2xlarge
gateload - c3.2xlarge

Tests
- [x] 1. 1 reader / 1 writer - #149 
- [x] 2. 2 readers / 1 writer - #150 
- [x] 3. 3 readers / 1 writer - #151 
- [x] 4. 4 readers / 1 writer - #152 
- [x] 5. 1 reader / 2 writers - #153 
- [x] 6. 2 readers / 2 writers - #154 
- [x] 7. 3 readers / 2 writers - #155
- [x] 8. 4 readers / 2 writers - #156

The test run results should be assembled into two matrices, one for P95 and another for P99 results, with the following layout:

Node Counts | 1 IR | 2 IR | 3 IR | 4 IR
----------- | ---- | ---- | ---- | ----
1 IW | Test 1 P95  | Test 2 P95  | Test 3 P95  | Test 4 P95 
2 IW | Test 5 P95  | Test 6 P95 | Test 7 P95  | Test 8 P95 

Node Counts | 1 IR | 2 IR | 3 IR | 4 IR
----------- | ---- | ---- | ---- | ----
1 IW | Test 1 P99  | Test 2 P99  | Test 3 P99  | Test 4 P99 
2 IW | Test 5 P99  | Test 6 P99 | Test 7 P99  | Test 8 P99 

EDIT gateload configuration to run for all the tests
```
{
    "Hostname": "{{ sync_gateway_private_ip }}",
    "Port": 4984,
    "AdminPort": 4985,
    "Database": "db",
    "DocSize": 1024,
    "SendAttachment": false,
    "RampUpIntervalMs": 300000,
    "RunTimeMs": 1200000,
    "SleepTimeMs": 10000,
    "NumPullers": {{ number_of_pullers }},
    "NumPushers": {{ number_of_pushers }},
    "ChannelActiveUsers": 40,
    "ChannelConcurrentUsers": 40,
    "MinUserOffTimeMs": 0,
    "MaxUserOffTimeMs": 0,
    "Verbose": false,
    "LogRequests": false,
    "UserOffset": {{ user_offset }},
    "AuthType": "basic",
    "Password": "password"
}
```

**Comment by sethrosetter** [comment]
@zgramana what hardware are we going to target for the individual pieces:

**Comment by zgramana** [comment]
Couchbase Server = 3 nodes for all configurations.

Hardware = perfcluster-aws

**Comment by sethrosetter** [comment]
@zgramana Thanks. To clarify: what EC2 instance types do we want for each element?

**Comment by zgramana** [comment]
Also, to clarify, keep the number of channels constant across these runs.

**Comment by sethrosetter** [comment]
@zgramana From the current perf stack, I have:

couchbase server - c3.8xlarge
sync_gateway -      c3.2xlarge
gateload -               m3.xlarge

Please take a look and verify this is what you want for the mini matrix.

**Comment by zgramana** [comment]
@sethrosetter M2 please.

**Comment by sethrosetter** [comment]
@zgramana It looks like M2 are previous generation EC2 instances. http://aws.amazon.com/ec2/previous-generation/ There are also multiple options. xlarge, 2xlarge, and 4xlarge

**Comment by zgramana** [comment]
Looks like `c3.2xlarge` should work for all nodes for this round.

**Comment by sethrosetter** [comment]
@zgramana @adamcfraser I will be using this config for the perf tests. I did a copy paste of the default config but changed logging from "*" to "REST+"

```
{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": true,
    "log":["HTTP+"],
    "verbose":"true",
    "cluster_config": {
        "server":"http://{{ couchbase_server_primary_node }}:8091",
        "data_dir":".",
        "bucket":"data-bucket"
    },
    "databases":{
        "db":{
            "feed_type":"DCPSHARD",
            "feed_params":{
                "num_shards":64
            },
            "server":"http://{{ couchbase_server_primary_node }}:8091",
            "bucket":"data-bucket",
            "users":{
                "GUEST":{
                    "disabled":true,
                    "admin_channels":[
                        "*"
                    ]
                }
            },
            "channel_index":{
                "server":"http://{{ couchbase_server_primary_node }}:8091",
                "bucket":"index-bucket",
                "writer":{{ is_index_writer }}
            }
        }
    }
}
```

**Comment by adamcfraser** [comment]
Setting verbose=true and log=HTTP+ are redundant - all verbose=true does is enable HTTP+ logging.

Now that https://github.com/couchbase/sync_gateway/issues/1321 has been merged, the feed_params section is obsolete, and num_shards should be moved under channel_index.  With this config, with num_shards not specified under channel_index, you'd be falling back to the default num_shards value of 64.

**Comment by sethrosetter** [comment]
@adamcfraser Does this look good as a perf default? I have removed num_shards so it should default to 64. 

```
{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": true,
    "log":["HTTP+"],
    "cluster_config": {
        "server":"http://{{ couchbase_server_primary_node }}:8091",
        "data_dir":".",
        "bucket":"data-bucket"
    },
    "databases":{
        "db":{
            "feed_type":"DCPSHARD",
            "server":"http://{{ couchbase_server_primary_node }}:8091",
            "bucket":"data-bucket",
            "users":{
                "GUEST":{
                    "disabled":true,
                    "admin_channels":[
                        "*"
                    ]
                }
            },
            "channel_index":{
                "server":"http://{{ couchbase_server_primary_node }}:8091",
                "bucket":"index-bucket",
                "writer":{{ is_index_writer }}
            }
        }
    }
}
```

**Comment by adamcfraser** [comment]
That looks fine.  A note for followup later, based on perf results:  num_shards=64 isn't going to be optimized for this sized cluster (you're doing much more partitioning that you need to).  I think it makes sense to stick with this for the initial mini-matrix (particularly since it's the default), but it's a data point to consider when reviewing the perf results.

**Comment by sethrosetter** [comment]
Node Counts | 1 IR | 2 IR | 3 IR | 4 IR
----------- | ---- | ---- | ---- | ----
1 IW | P95 = 11.125350047s   | P95 = 1.271452905s | P95 = 1.11763358733s | Test 4 P95 
2 IW | Test 5 P95  | Test 6 P95 | Test 7 P95  | Test 8 P95 

Node Counts | 1 IR | 2 IR | 3 IR | 4 IR
----------- | ---- | ---- | ---- | ----
1 IW | P99 = 13.609105253 | P99 = 1.417369437s | P99 = 1.16604896867s | Test 4 P99 
2 IW | Test 5 P99  | Test 6 P99 | Test 7 P99  | Test 8 P99

**Comment by sethrosetter** [comment]
After chatting with @adamcfraser and @waynecarter, we are going to re rerun the matrix with the following changes. I will be using the same hardware and same topology matrix.

- 10k pushers /10k pullers per cluster
- 30 min test run time

Also, we want to track additional variables
- resource CPU
- memory stats.

@adamcfraser can you provide the specific sync_gateway expvars to track for memory usages?

**Comment by sethrosetter** [comment]
Hardware specs
3 Couchbase Servers - c3.2xlarge
sync_gateway - c3.2xlarge
gateload - c3.2xlarge

Tests
- [x] 1. 1 reader / 1 writer - #149 
- [x] 2. 2 readers / 1 writer - #150 
- [x] 3. 3 readers / 1 writer - #151 
- [x] 4. 4 readers / 1 writer - #152 
- [x] 5. 1 reader / 2 writers - #153 
- [x] 6. 2 readers / 2 writers - #154 
- [x] 7. 3 readers / 2 writers - #155
- [x] 8. 4 readers / 2 writers - #156

Node Counts | 1 IR | 2 IR | 3 IR | 4 IR
----------- | ---- | ---- | ---- | ----
1 IW | Test 1 P95  | Test 2 P95  | Test 3 P95  | Test 4 P95 
2 IW | Test 5 P95  | Test 6 P95 | Test 7 P95  | Test 8 P95 

Node Counts | 1 IR | 2 IR | 3 IR | 4 IR
----------- | ---- | ---- | ---- | ----
1 IW | Test 1 P99  | Test 2 P99  | Test 3 P99  | Test 4 P99 
2 IW | Test 5 P99  | Test 6 P99 | Test 7 P99  | Test 8 P99

**Comment by adamcfraser** [comment]
@sethrosetter The memstats block of the Sync gateway expvars contain the memory info.  We've used memstats.Alloc from the Sync Gateway expvars to monitor whether memory usage is stable for a given test, but I think you'd want to use Sys for the total memory allocated to the process by the OS.  I don't think it's 1:1 with what you see from something like top, but it's probably close enough for this exercise.

More details on the various memstats properties here:
https://golang.org/pkg/runtime/#MemStats

**Comment by sethrosetter** [comment]
10k pushers /10k pullers per cluster
30 min test run time

Hardware specs
3 Couchbase Servers - c3.2xlarge
sync_gateway - c3.2xlarge
gateload - c3.2xlarge

Tests
- [ ] 1. 1 reader / 1 writer - #149 
- [ ] 2. 2 readers / 1 writer - #150 
- [ ] 3. 4 readers / 1 writer - #151 
- [ ] 4. 8 readers / 1 writer - #152 
- [ ] 5. 1 reader / 2 writers - #153 
- [ ] 6. 2 readers / 2 writers - #154 
- [ ] 7. 4 readers / 2 writers - #155
- [ ] 8. 8 readers / 2 writers - #156

Node Counts | 1 IR | 2 IR | 4 IR | 8 IR
----------- | ---- | ---- | ---- | ----
1 IW | Test 1 P95  | Test 2 P95  | Test 3 P95  | Test 4 P95 
2 IW | Test 5 P95  | Test 6 P95 | Test 7 P95  | Test 8 P95 

Node Counts | 1 IR | 2 IR | 4 IR | 8 IR
----------- | ---- | ---- | ---- | ----
1 IW | Test 1 P99  | Test 2 P99  | Test 3 P99  | Test 4 P99 
2 IW | Test 5 P99  | Test 6 P99 | Test 7 P99  | Test 8 P99
