### ISSUE TITLE
Collect CBGT diagnostics via REST API on functional test failures

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/sync-gateway-testcluster#157]
As described in https://github.com/couchbase/sync_gateway/issues/1371#issuecomment-165633686, we need to collect CBGT diagnostics whenever a functional test fails.

1. Choose any Sync Gateway index writer node that is still running
1. Make an HTTP call to `HOST:4985/_cbgt/api/diag`
1. Store the value in a file or attach to the Jenkins job

**Comment by sethrosetter** [comment]
@tleyden I think we can close this, right?

**Comment by tleyden** [comment]
Yep
