### ISSUE TITLE
DCP Reshard test might not be waiting long enough

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/sync-gateway-testcluster#161]
Currently it waits 10 seconds before requesting the changes feed, but since the reshard process can have some delay (30+ seconds?), this needs to wait longer for this particular test.

[func test 207](http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests-distributed-index/207/parameters/) succeeded five times with a sleep time of 120s, whereas [func test 208](http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests-distributed-index/207/parameters/) failed the first time with a sleep time of 10s

**Comment by ashvindersingh** [comment]
Did this test pass on every run or just 5 times out of x runs? 120 seconds is lot of delay.

**Comment by tleyden** [comment]
With the 120 seconds delay it passed approx 14/15 times.

With 60 seconds delay it passed 4/5 times.

With the 10s delay I only tried it once, and it failed that one time.

Note: this [workaround](https://github.com/couchbase/sync_gateway/issues/1371#issuecomment-165670607) must be in place to pass, which is in-place for the functional tests I listed above.

As a compromise, how about 60 seconds?

**Comment by ashvindersingh** [comment]
What is the ideal duration of dcp_reshard time we should be expecting? I agree with having #167.

**Comment by tleyden** [comment]
It's a polling mechanism .. I think we should allow at least 30 seconds for the reshard to happen, and there is additional time for the indexing.

**Comment by ashvindersingh** [comment]
ok fair enough.
