### ISSUE TITLE
[Distributed Index] Run Gateload on multiple IR / IW topologies with 5K / 5k #2

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/sync-gateway-testcluster#205]
The mini matrix was run against the feature/distributed_index branch before access work and merge down to master had occurred. Those result can be found in #140

These results are targeted for the 1.2 release post merge and access work. All results will be tracked on this ticket.

There are a few changes from the mini matrix in #140:
- RampUpIntervalMs is now 2 min instead of 5 min
- RunTimeMs is now 40 min

Run 8 tests where the only variable is the specific index reader / writer ratio. These tests should all use the following test parameters: 5k writers per cluster / 5k readers per cluster / 1KB docs.

EDIT: Hardware specs
3 Couchbase Servers - c3.2xlarge
sync_gateway - c3.2xlarge
gateload - c3.2xlarge

Tests
- [x] 1. 1 reader / 1 writer
- [x] 2. 2 readers / 1 writer
- [x] 3. 3 readers / 1 writer 
- [x] 4. 4 readers / 1 writer
- [x] 5. 8 readers / 1 writer
- [x] 6. 1 reader / 2 writers 
- [x] 7. 2 readers / 2 writers 
- [x] 8. 3 readers / 2 writers
- [x] 9. 4 readers / 2 writers
- [x] 10. 8 readers / 2 writers

The test run results should be assembled into two matrices, one for P95 and another for P99 results, with the following layout:

### P99 - gateload.PushToSubscriberInteractive.p99 (seconds)

Note: The 1 IW scenarios were done at a different time on a different cluster that the 2 IW.

Node Counts | 1 IR | 2 IR | 3 IR | 4 IR | 8 IR
----------- | ---- | ---- | ---- | ---- | ----
1 IW | P95 - 81.28  | P95 - 1.77 | P95 1.46 | P95 - 1.53 | P95 - 1.46
2 IW | P95 - 73.00  | P95 - 2.11 | P95 - 1.78 | P95 - 1.60 | P95 - 1.47

Node Counts | 1 IR | 2 IR | 3 IR | 4 IR | 8 IR
----------- | ---- | ---- | ---- | ---- | ----
1 IW | P99 - 129.63  | P99 - 2.30 | P99 - 1.73 | P99 - 1.75 | P99 -1.58
2 IW | P99 - 102.22  | P99 - 3.19 | P99 - 4.86 | P99 - 2.05 | P99 - 1.61

EDIT gateload configuration to run for all the tests
```
{
    "Hostname": "{{ sync_gateway_private_ip }}",
    "Port": 4984,
    "AdminPort": 4985,
    "Database": "db",
    "DocSize": 1024,
    "SendAttachment": false,
    "RampUpIntervalMs": 120000,
    "RunTimeMs": 2400000,
    "SleepTimeMs": 10000,
    "NumPullers": {{ number_of_pullers }},
    "NumPushers": {{ number_of_pushers }},
    "ChannelActiveUsers": 40,
    "ChannelConcurrentUsers": 40,
    "MinUserOffTimeMs": 0,
    "MaxUserOffTimeMs": 0,
    "Verbose": false,
    "LogRequests": false,
    "UserOffset": {{ user_offset }},
    "AuthType": "basic",
    "Password": "password"
}
```

**Comment by sethrosetter** [comment]
Currently,  this is waiting on https://github.com/couchbase/sync_gateway/issues/1405

**Comment by sethrosetter** [comment]
Targeting 1.2.0-50
## 1IR / 1IW
Full results - https://s3.amazonaws.com/sync-gateway-logs/perf_tests/1.2.0-50/5k-5k-1IR-1IW_2016-01-17-18-36-44.zip
## 2IR / 1IW
Full results - https://s3.amazonaws.com/sync-gateway-logs/perf_tests/1.2.0-50/5k-5k-2IR-1IW_2016-01-17-17-34-12.zip
## 3IR / 1IW
Full results - https://s3.amazonaws.com/sync-gateway-logs/perf_tests/1.2.0-50/5k-5k-3IR-1IW_2016-01-17-16-40-01.zip
## 4IR / 1IW
Full results - https://s3.amazonaws.com/sync-gateway-logs/perf_tests/1.2.0-50/5k-5k-4IR-1IW_2016-01-17-15-40-21.zip
## 8IR / 1IW
Full results - https://s3.amazonaws.com/sync-gateway-logs/perf_tests/1.2.0-50/5k-5k-8IR-1IW_2016-01-17-23-09-29.zip

## 1IR / 2IW
Full results - https://s3.amazonaws.com/sync-gateway-logs/perf_tests/1.2.0-50/5k-5k-1IR-2IW_2016-01-16-21-35-53.zip
## 2IR / 2IW
Full results - https://s3.amazonaws.com/sync-gateway-logs/perf_tests/1.2.0-50/5k-5k-2IR-2IW_2016-01-16-20-37-03.zip
## 3IR / 2IW
Full results - https://s3.amazonaws.com/sync-gateway-logs/perf_tests/1.2.0-50/5k-5k-3IR-2IW_2016-01-16-19-39-37.zip
## 4IR / 2IW
Full results - https://s3.amazonaws.com/sync-gateway-logs/perf_tests/1.2.0-50/5k-5k-4IR-2IW_2016-01-16-18-35-23.zip
## 8IR / 2IW
Full results - https://s3.amazonaws.com/sync-gateway-logs/perf_tests/1.2.0-50/5k-5k-8IR-2IW_2016-01-17-22-12-22.zip

**Comment by sethrosetter** [comment]
## 2IR / 1IW
Full results - https://s3.amazonaws.com/sync-gateway-logs/perf_tests/1.2.0-50/5k-5k-2IR-1IW_2016-01-17-17-34-12.zip

**Comment by sethrosetter** [comment]
## 3IR / 1IW
Full results - https://s3.amazonaws.com/sync-gateway-logs/perf_tests/1.2.0-50/5k-5k-3IR-1IW_2016-01-17-16-40-01.zip

**Comment by sethrosetter** [comment]
## 4IR / 1IW
Full results - https://s3.amazonaws.com/sync-gateway-logs/perf_tests/1.2.0-50/5k-5k-4IR-1IW_2016-01-17-15-40-21.zip

**Comment by sethrosetter** [comment]
## 8IR / 1IW
Full results - https://s3.amazonaws.com/sync-gateway-logs/perf_tests/1.2.0-50/5k-5k-8IR-1IW_2016-01-17-23-09-29.zip

**Comment by sethrosetter** [comment]
## 1IR / 2IW
Full results - https://s3.amazonaws.com/sync-gateway-logs/perf_tests/1.2.0-50/5k-5k-1IR-2IW_2016-01-16-21-35-53.zip

**Comment by sethrosetter** [comment]
## 2IR / 2IW
Full results - https://s3.amazonaws.com/sync-gateway-logs/perf_tests/1.2.0-50/5k-5k-2IR-2IW_2016-01-16-20-37-03.zip

**Comment by sethrosetter** [comment]
## 3IR / 2IW
Full results - https://s3.amazonaws.com/sync-gateway-logs/perf_tests/1.2.0-50/5k-5k-3IR-2IW_2016-01-16-19-39-37.zip

**Comment by sethrosetter** [comment]
## 4IR / 2IW
Full results - https://s3.amazonaws.com/sync-gateway-logs/perf_tests/1.2.0-50/5k-5k-4IR-2IW_2016-01-16-18-35-23.zip

**Comment by sethrosetter** [comment]
## 8IR / 2IW
Full results - https://s3.amazonaws.com/sync-gateway-logs/perf_tests/1.2.0-50/5k-5k-8IR-2IW_2016-01-17-22-12-22.zip

**Comment by sethrosetter** [comment]
# Targeting 1.2.0-54
## 8IR / 2IW
Full results -

**Comment by sethrosetter** [comment]
# Targeting 1.2.0-54
## 4IR / 2IW
Full results -

**Comment by sethrosetter** [comment]
# Targeting 1.2.0-54
## 3IR / 2IW
Full results -

**Comment by sethrosetter** [comment]
# Targeting 1.2.0-54
## 2IR / 2IW
Full results -

**Comment by sethrosetter** [comment]
# Targeting 1.2.0-54
## 1IR / 2IW
Full results -

**Comment by adamcfraser** [comment]
# Targeting 1.2.0-54
## 8IR / 1IW
Full results - https://s3.amazonaws.com/sync-gateway-logs/perf_tests/1.2.0-54/5k-5k-8IR-1IW_2016-01-18-21-44-47.zip

**Comment by adamcfraser** [comment]
# Targeting 1.2.0-54
## 4IR / 1IW
Full results - https://s3.amazonaws.com/sync-gateway-logs/perf_tests/1.2.0-54/5k-5k-4IR-1IW_2016-01-19-01-24-23.zip

**Comment by adamcfraser** [comment]
# Targeting 1.2.0-54
## 4IR / 1IW
Full results - https://s3.amazonaws.com/sync-gateway-logs/perf_tests/1.2.0-54/5k-5k-3IR-1IW_2016-01-19-02-44-35.zip

**Comment by adamcfraser** [comment]
# Targeting 1.2.0-54
## 2IR / 1IW
Full results - https://s3.amazonaws.com/sync-gateway-logs/perf_tests/1.2.0-54/5k-5k-2IR-1IW_2016-01-19-10-24-57.zip

**Comment by adamcfraser** [comment]
# Targeting 1.2.0-54
## 1IR / 1IW
Full results - https://s3.amazonaws.com/sync-gateway-logs/perf_tests/1.2.0-54/5k-5k-1IR-1IW_2016-01-19-11-27-26.zip

**Comment by sethrosetter** [comment]
@zgramana Updated the table. Can you close once you have reviewed?

**Comment by adamcfraser** [comment]
# Targeting 1.2.0-69
## 4IR/2IW
Full results - https://s3.amazonaws.com/sync-gateway-logs/perf_tests/1.2.0-69/5k-5k-4IR-2IW_2016-01-28-13-26-05.zip

![gateload_expvars](https://cloud.githubusercontent.com/assets/8866453/12662261/f604bad8-c5d3-11e5-98e4-5172021c1cc3.png)
![sync_gateway_expvars](https://cloud.githubusercontent.com/assets/8866453/12662265/fb73c48c-c5d3-11e5-9ca5-6e406b220282.png)
![sync_gateway_machine_stats](https://cloud.githubusercontent.com/assets/8866453/12662268/fe12ea74-c5d3-11e5-9aec-a8be4233d59b.png)

**Comment by adamcfraser** [comment]
# Targeting 1.2.0-69
## 2IR/2IW
Full results - https://s3.amazonaws.com/sync-gateway-logs/perf_tests/1.2.0-69/5k-5k-2IR-2IW_2016-01-28-15-11-17.zip
