### ISSUE TITLE
Add test for invalid distributed index configurations

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/sync-gateway-testcluster#221]
-Scenario
- Have the writer launch successfully
- Launch the reader omitting "writer" property

**Comment by adamcfraser** [comment]
This looks like it's working as intended for me.

Started a local Sync Gateway with the following config (running as reader, with writer property omitted), and it started successfully and returned valid results on a _changes request.

Config:
```
{
   "interface":":4984",
   "adminInterface":":4985",
   "log":["*"],
   "databases": {
      "default": {
        "server": "http://localhost:8091",
        "bucket": "default",
        "users": {
            "GUEST": { "disabled": true }
        },
        "channel_index": {
        	"server":"http://localhost:8091",
        	"bucket":"channel_index"
        }
      }
   }
}
```
