### ISSUE TITLE
Spin up AWS testing endpoint for TodoLite

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/sync-gateway-testcluster#229]
- Endpoint for distributed index mode
- Endpoint for channel cache mode

**Comment by tleyden** [comment]
@hidek can you please try to smoke-test todolite android against this Sync Gateway 1.2 instance?  @pasin can you do the same for todolite ios?  Todolite should be using the 1.2 version of couchbase lite.

http://ec2-54-145-244-2.compute-1.amazonaws.com:4984/todolite-cc/

I've done no testing so far, other than to curl the above URL.

**Comment by tleyden** [comment]
@hideki / @pasin Oops, just realized that it's not configured for facebook login.  Will fix

**Comment by tleyden** [comment]
@hideki / @pasin ok it has been redeployed with an updated config:  https://github.com/couchbaselabs/sync-gateway-testcluster/pull/230/files

**Comment by tleyden** [comment]
@pasin in the ios case, what would be *ideal* would be to have an .apk of todo-lite signed by an enterprise license that can be distributed in-house to mobile team folks, pointed to the url mentioned above.

I did this recently for an app and it wasn't too painful, and I was able to publish it to s3 and download on any device.  I can help if needed.

**Comment by tleyden** [comment]
I did a smoke test against http://ec2-54-145-244-2.compute-1.amazonaws.com:4984/todolite-cc/ with todolite-ios and didn't see any issues

**Comment by tleyden** [comment]
OTOH, smoke test against http://ec2-54-145-244-2.compute-1.amazonaws.com:4984/todolite-di/ is giving these errors:

https://gist.github.com/tleyden/f1f3665986029a4e825b

**Comment by tleyden** [comment]
I just added grocery-sync:

http://ec2-54-145-244-2.compute-1.amazonaws.com:4984/grocery-sync/

It's using this configuration:

```
	"grocery-sync": {
			"server": "http://{{ couchbase_server_primary_node }}:8091",
			"bucket": "grocery-sync",
			"users": {
				"GUEST": {"disabled": false, "admin_channels": ["*"] }
			}
	},
```
