### ISSUE TITLE
.NET 1.2 release tasks

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/sync-gateway-testcluster#252]
- [x] verify SimpleAndroidSync with sync_gateway 1.2
    - [x] Try with Channel Cache
    - [x] Try with Distributed Index
- [x] verify CouchbaseSample.iOS with sync_gateway 1.2
    - [x] Try with Channel Cache
    - [x] Try with Distributed Index
- [x] db online / offline spot checking

**Comment by sethrosetter** [comment]
Waiting on a retest after https://github.com/couchbase/couchbase-lite-net/issues/556 is closed

**Comment by zgramana** [comment]
Thanks. Can you move this over to couchbase-lite-net?

**Comment by sethrosetter** [comment]
moved to tracking - https://github.com/couchbase/couchbase-lite-net/issues/564
