### ISSUE TITLE
Automate AMI image creation for SG 1.2

### ISSUE THREAD

**Issue by ashvindersingh** [couchbaselabs/sync-gateway-testcluster#279]

**Comment by ashvindersingh** [comment]
AMI image has been created. 
Review ongoing.

**Comment by ashvindersingh** [comment]
https://issues.couchbase.com/browse/CBIT-4546

**Comment by zgramana** [comment]
@tleyden to help out.

**Comment by ashvindersingh** [comment]
Created AMIs for both enterprise and community editions of SG-1.2.0-79
Enterprise AMI : ami-832613e9
Community AMI: ami-35b59c5f
