### ISSUE TITLE
Functional test for CBSE-2399

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/sync-gateway-testcluster#291]
From @adamcfraser:

We don't currently have any bucket shadowing tests in the functional test suite, and it's difficult to cover the breadth of bucket shadowing scenarios using only unit tests.

An example is the issue described in https://issues.couchbase.com/browse/CBSE-2399.  In that scenario SG is panicking looking for a non-existent parent ID.  The symptom (panic) is being addressed by https://github.com/couchbase/sync_gateway/issues/1603, but functional tests would help get to the root cause. 

For the linked issue in particular, it's possibly related to historical data present in the mutation feed.  Bucket shadowing always restarts the feed from zero on Sync Gateway startup, so it's more likely to hit issues with historical feed data.

Hypothesis is that there is historical data present on the feed that results in the missing parent.  One possible test case might be:

1. Start Sync Gateway using bucket shadowing.
1. Add doc to bucket via source bucket
1. Delete a document in the source bucket.
1. Restart Sync Gateway

The issue may be a race condition depending on when #4 happens relative to #3 (i.e. whether the document has been pulled/pushed).

**Comment by tleyden** [comment]
From me:

> Is there any temporal requirement between 2) and 3)? I mean, does 3) have to happen immediately after 2) or can there be a long delay and it should still reproduce the problem?

From @adamcfraser:

> @tleyden I don't think we know yet.  I'm trying to dig into the exact sequence of events.  At some point I think Couchbase Server may remove the historical entry from the TAP feed and this problem may go away, but it's not clear yet whether there's a race around #2 and #3.

**Comment by adamcfraser** [comment]
Still no obvious scenario to reproduce from the CBSE, but some more information was added:
- Couchbase cluster was restored from backup at some point to 'reset' a testing scenario.  It's not known whether clients were reset - this could be resulting from clients pushing a pre-restore document to a post-restore DB.
- The gap between the problematic revision (generation 640-xxx) and the current revision (generation 1797-xxx) was greater than the default revs_limit, so this may still be related to https://github.com/couchbase/sync_gateway/issues/959.

Unlike #959, this wouldn't be triggered by high throughput - instead it would be something to do with the backup/restore.

**Comment by ajres** [comment]
I have reproduced the log output with the following manual test, it's not an exact reproduction but I think a variant of this could repro the original CBSE case.

1) Setup SG Bucket and Shadow bucket and start SG with shadow config.

2) Create a new doc via REST API, this will create a doc in shadow and will set the "upstream-rev" property on the SG doc metadata

3) Take shadow offline (I deleted the CBS bucket I don't know if a restore will have the same effect)

4) While shadow is offline, update the doc enough times to exceed the revs_limit setting. This will updated the doc but will not update the "upstream_rev" property. 

4a) Delete doc, this will generate the following log message in the SG log

Shadow: Pushing "doc1", rev "9-ebbae742633c5059d80a062db256e1cb" [deletion]
2016-02-25T19:28:47.851Z WARNING: Error pushing rev of "doc1" to external bucket: MCResponse status=0x20, opcode=SASL_AUTH, opaque=0, msg: Auth failure -- db.(*Shadower).PushRevision() at shadower.go:164

5) Bring shadow back online

6) Edit document in shadow
 
SG will panic with log message:

2016-02-25T19:30:29.167Z Shadow+: Pulling "doc1", CAS=7eb93f972df71 ... have UpstreamRev="1-1e9dec7ea42713475896b0f1a5074a20", UpstreamCAS=c8203a57f0
panic: parent id "1-1e9dec7ea42713475896b0f1a5074a20" is missing

**Comment by tleyden** [comment]
Is it reliably reproducible?

**Comment by ajres** [comment]
Yes, it is reproducible,  I'm just not sure how close to the original usage scenario it is.

**Comment by tleyden** [comment]
@ajres I'm going to try to modify [this test](https://github.com/couchbaselabs/sync-gateway-testcluster/blob/feature/issue_291_func_test_bucket_shadow/functional_tests/test_bucket_shadow.py) with those repro steps.

Questions:

> 3) Take shadow offline (I deleted the CBS bucket I don't know if a restore will have the same effect)

So you just deleted the bucket in the CB UI?  I'll plan to do the same via a REST call to CB Server.

> 5) Bring shadow back online

So you just created the bucket in the CB UI?

> update the doc enough times to exceed the revs_limit setting

Which value did you use?  Actually,  can you post your entire SG config to a gist?

**Comment by ajres** [comment]
config gist https://gist.github.com/ajres/e2756715dc93b24e603d

3) Yes just deleted.

5) Created the shadow bucket again, actually had to restart SG at that point. I don;t know if a restore would require that.

For my own sanity I used revs_limit = 5, but I don;t think the actual value impacts this test other than the number of doc updates required repro.

**Comment by ashvindersingh** [comment]
Thanks @ajres! I'm able to reproduce the issue with backup and restore too. Here are the exact steps which I followed with minor variation: 

SG build: 1.2.0-79
CB build: 3.1.0-1776
Couchbaselite version: 1.2.0-101

1. Setup bucket shadowing. Sync gateway config: https://gist.github.com/b6afb778d7e2ae7a4f99. Also have 'revs_limit' to 3
2. git clone https://github.com/couchbaselabs/Grocery-Sync-iOS and point the app to your sg url in DemoAppDelegate.m. Launch
3. Create one item on grocery sync app
4. Ensure it gets copied/replicated to shadowed bucket. 
5. Now take a backup of the shadow bucket: ./cbbackup http://localhost:8091 /root/backup
6. Delete the shadow bucket. Create a new bucket. Ensure its online. 
7. Update the item on simulator or device more than 3 times or greater than your revs_limit
8. Delete the document/item from the simulator/device
9. Observe: Sync gateway by default doesn't connect back with newly created shadow bucket*. 

```
2016/02/25 14:09:44 go-couchbase: TAP connection lost; reconnecting to bucket "source" in 1s
2016/02/25 14:09:45 go-couchbase: TAP connection lost; reconnecting to bucket "source" in 2s
2016/02/25 14:09:47 go-couchbase: TAP connection lost; reconnecting to bucket "source" in 4s
2016/02/25 14:09:51 go-couchbase: TAP connection lost; reconnecting to bucket "source" in 8s
2016/02/25 14:09:59 go-couchbase: TAP connection lost; reconnecting to bucket "source" in 16s
```
10. Do a cbrestore on the shadow bucket with ./cbrestore /root/backup http://172.23.106.74:8091 --bucket-source=source
11. Restart sync gateway and verify it gets connected with shadow bucket.
12. From the web console of the shadow bucket edit the document. 
13. Notice panic in sync gateway;
```
2016-02-25T14:11:38.553-08:00 Shadow: Reading history of external bucket
2016-02-25T14:11:38.622-08:00 Shadow: Caught up with history of external bucket
2016-02-25T14:11:58.781-08:00 Shadow+: Pulling "-dHSCFPWbKsajHRYyEtKiqR", CAS=438addfa96c5d7 ... have UpstreamRev="1-552518884fa1a7622b79dd053bb87539", UpstreamCAS=c8204969a0
panic: parent id "1-552518884fa1a7622b79dd053bb87539" is missing

```

**Comment by tleyden** [comment]
> 5) Created the shadow bucket again, actually had to restart SG at that point. I don;t know if a restore would require that.

Can you elaborate on that?  What forced you to restart?  (it just never saw the source/shadow bucket?)

**Comment by ashvindersingh** [comment]
I believe that "TAP connection lost" may be the reason. I noticed it too. After deleting a shadow bucket the sync gateway doesn't connect with the shadow bucket again unless you restart sync gateway.

**Comment by tleyden** [comment]
Cool, thanks @ashvindersingh

**Comment by tleyden** [comment]
The test is in progress, but I ran into a [snag](https://github.com/couchbaselabs/sync-gateway-testcluster/blob/feature/issue_291_bucket_shadow_repro/functional_tests/test_bucket_shadow.py#L88-L89) with the bucket recreation

**Comment by tleyden** [comment]
Question from meeting: if you have 3 SG nodes, and only 1 configured as a shadower, but the update came in the non-shadower: what happens?   Same test, but temporarily take the shadow offline during the update: what happens?

**Comment by tleyden** [comment]
Should bucket be taken offline if shadow bucket is not available?

**Comment by tleyden** [comment]
1. Spin up SG with 2 running nodes, 1 in shadower, 1 normal
1. Two cb server bucket: source and data
1. Revs limit = default
1. Write several docs into shadower SG
1. Write several docs into non-shadower SG 
1. Ditto as above, but bump revs rather than writing brand new docs
1. Kill -9 sync gateway the SG shadower
1. Write several docs + bump revs into non-shadower SG 
1. Bring SG shadower 
1. Verify SG shadower comes up without panicking, given writes from non-shadower during downtime.

**Comment by ashvindersingh** [comment]
Running the above steps(1-11) manually does not cause the panic in either the shadower sync gateway or non shadower sync gateway. 
For generating the data and revisions  used https://github.com/couchbaselabs/sync-gateway-testcluster/blob/master/functional_tests/test_single_user_single_channel_doc_updates.py.

**Comment by tleyden** [comment]
I wasn't able to reproduce it with this automated test: https://github.com/couchbaselabs/sync-gateway-testcluster/blob/c2916699c77dd28b713546aec504e7343048f1d0/functional_tests/test_bucket_shadow.py#L12-L84

**Comment by tleyden** [comment]
Todo: write the following tests

```

    # TODO: set revs limit to 40
    #       while shadower offline, update one doc more than 50 times
    #       bring shadower
    #       look for panics

    # TODO: flavors of delete
    #       doc exists that has been pushed to source bucket
    #       while shadower offline
    #       bring shadower online, look for panics and failed delete operations (only option is to looking in logs .. manually)

    # TODO: take shadower offline
    #       write one new doc
    #       bring shadower online
    #       check whether new doc is pushed to source bucket
    #       assert that it does, fail test if not

    # TODO: start tap pusher from zero (hack)
    #       rerun above tests (in particular revs limit 40 test)

    #	listener.TapArgs = sgbucket.TapArguments{
    #		Backfill: sgbucket.TapNoBackfill,  // <--- set that to 0 instead of TapNoBackfill
    #		Notify:   notify,
    #	}

```

**Comment by tleyden** [comment]
@adamcfraser this test is reproducing a failure:

```
# TODO: take shadower offline
    #       write one new doc
    #       bring shadower online
    #       check whether new doc is pushed to source bucket
    #       assert that it does, fail test if not
```

which is probably not too surprising.

**Comment by tleyden** [comment]
@adamcfraser for this:

>     #       bring shadower online, look for panics and failed delete operations (only option is to looking in logs .. manually)

what should I be looking for?  searching for "error" or "fail" is turning up empty

**Comment by tleyden** [comment]
I tried this modification on a sync gateway branch:

```
# TODO: start tap pusher from zero (hack)
    #       rerun above tests (in particular revs limit 40 test)

    #   listener.TapArgs = sgbucket.TapArguments{
    #       Backfill: sgbucket.TapNoBackfill,  // <--- set that to 0 instead of TapNoBackfill
    #       Notify:   notify,
    #   }
```

and all the current tests I have currently enabled were passing, so that Sync Gateway change didn't seem to change anything.

**Comment by tleyden** [comment]
Todo: add test where you add (and then delete) a non-winning revision.

**Comment by adamcfraser** [comment]
Have been able to reproduce in a similar fashion to Andy, but without disabling the shadower or using multiple node, by:

1. Set revs_limit to 5
2. Create a doc via SG
3. Issue a delete operation for that doc via SG  
4. Repeat step 3 5x.  (each additional delete will create a new revision in SG, but the delete on the source bucket will fail with the 'not found' error, which also means that upstream_rev won't get incremented
5. Recreate the doc in the source bucket

At this point SG will panic, and continue to panic on subsequent startup.

**Comment by adamcfraser** [comment]
Options to resolve and recover from the panic scenario:

1. Delete doc in source bucket.  If doc is deleted in SG bucket, this returns to expected state. If the doc isn't deleted in the SG bucket, it may not be pushed to the source bucket until the next revision for that doc.
Recommended when: The doc has already been tombstoned in the SG bucket

2. Remove upstream_rev and upstream_cas from _sync metadata in SG bucket.  Version of doc from source bucket will be applied to the SG bucket as a new revision tree branch with no parent (new root branch).  Normal conflict resolution may be required.
Recommended when: Both the SG and source bucket version of the doc have valid data that should be treated as a standard revision tree conflict.

3. Apply hotfix.  Version of doc from source bucket will be applied to the SG bucket as a new revision tree branch with no parent (new root branch). Normal conflict resolution may be required.  Source version of the doc will be added as a revision even if the SG version had been tombstoned.
Recommended when: When automated handling is desirable, and you don't need to differentiate between #1 and #2.

**Comment by tleyden** [comment]
Regarding steps to repro in https://github.com/couchbaselabs/sync-gateway-testcluster/issues/291#issuecomment-191521993, this only produces a warning rather than a panic due to https://github.com/couchbase/sync_gateway/pull/1617

```
2016-03-03T21:36:13.604Z WARNING: Shadow: Adding revision as conflict branch, parent id "19-fa94997495d8ed3b4bbe4d3bb38f7ced" is missing
-- db.(*Shadower).pullDocument.func1() at shadower.go:130
```

**Comment by tleyden** [comment]
I just verified that against Sync Gateway commit https://github.com/couchbase/sync_gateway/commit/0adf2e32e99de4bd77b0878e435fba18ca5cdf1a, and [this functional test](https://gist.github.com/tleyden/3669cd0e42f31db7160e#file-gistfile2-txt) I'm able to produce this [panic](https://gist.github.com/tleyden/3669cd0e42f31db7160e#file-gistfile1-txt)

Which shows that https://github.com/couchbase/sync_gateway/pull/1617 does prevent the panic.

**Comment by tleyden** [comment]
Once https://github.com/couchbaselabs/sync-gateway-testcluster/pull/319 is merged, this can be closed.
