### ISSUE TITLE
Ansible SSH error which appears related to El Capitan

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/sync-gateway-testcluster#294]
Running

```
ansible -vvvv sync_gateways -u centos -i provisioning_config -m command -a 'ls -al /tmp'
```

is giving me this error:

https://gist.github.com/tleyden/2d6b43d5318e11e357c3

Appears to be related to https://github.com/ansible/ansible/issues/11536, but none of the fixes on that issue have worked for me so far.  (I was adding the modified config in `provision/ansible/playbooks/ansible.cfg`)

**Comment by tleyden** [comment]
Just noticed this in the output

```
No config file found; using defaults
```

Does that mean it's not picking up the `provision/ansible/playbooks/ansible.cfg` file?  I just removed a closing brace in that file, and it didn't seem to break anything, so it looks like that file is being ignored for me.  Actually, that makes sense, since I'm not running an ansible playbook.

**Comment by tleyden** [comment]
That was the problem.  The following worked for me:

Change `provision/ansible/playbooks/ansible.cfg` to:

```
[defaults]
remote_user = centos

[ssh_connection]
control_path = %(directory)s/%%C

```

set `ANSIBLE_CONFIG` to point to that ansible.cfg file: 

```
$ export ANSIBLE_CONFIG="/Users/tleyden/Development/sync-gateway-testcluster/provision/ansible/playbooks/ansible.cfg"
```

Now this works:

```
ansible -vvvv sync_gateways -u centos -i provisioning_config -m command -a 'ls -al /tmp'
```

**Comment by tleyden** [comment]
Yikes!  Just noticed we already have effectively the same fix in https://github.com/couchbaselabs/sync-gateway-testcluster/blob/master/provision/ansible/playbooks/ansible.cfg.example

The problem was my local `provision/ansible/playbooks/ansible.cfg`, which hadn't been updated.

@sethrosetter hey is there still a need to have `ansible.cfg.example` be a `.example` file, or can we just default to `user=centos`.  Do you still need to connect to any VM's as root?

**Comment by sethrosetter** [comment]
@tleyden I think we still need the example. I use this often for vms as well as AWS. Perhaps we could hide it somehow and pass a --user flag or something. I have no problem changing the .example default but that would not address your situation where the cfg was stale.
