### ISSUE TITLE
Add ansible.cfg.example to performance_tests/ansible/playbooks

### ISSUE THREAD

**Issue by ajres** [couchbaselabs/sync-gateway-testcluster#33]
When running performance tests I also needed to create an 'ansible.cfg' file in the performance_tests/ansible/playbook directory.

Should we add ansible.cfg.example and instructions similar to the existing 'Setup Global Ansible Config' section?

$ cd sync-gateway-testcluster/performance_tests/ansible/playbooks
$ cp ansible.cfg.example ansible.cfg
$ vi ansible.cfg  # edit to your liking

**Comment by tleyden** [comment]
@ajres sure, I don't see any problem with that!
