### ISSUE TITLE
Recreate Jenkins slave

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/sync-gateway-testcluster#340]
Related jira ticket: https://issues.couchbase.com/browse/CBIT-4826

**Comment by tleyden** [comment]
- [ ] Find old VM used for functional tests -- increase resources on that VM

**Comment by sethrosetter** [comment]
Slave is back. http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests/155/. I fixed the clock sync issue and updated the dep on our old runner. If some tests fail do to resources, we may need to bump the specs but tests are running again.

**Comment by sethrosetter** [comment]
Closing criteria - Stable http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests run.

**Comment by sethrosetter** [comment]
Stable enough - http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests/167/#showFailuresLink
