### ISSUE TITLE
Tests hang

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/sync-gateway-testcluster#37]
If the sync gateway changes feed hangs indefinitely, the `test_single_user_single_channel.py` test will also hang indefinitely (there might be some eventual timeout, but it's a long time)

**Comment by sethrosetter** [comment]
@tleyden We added request timeouts. Are you still seeing this behavior after a pull from master?

**Comment by tleyden** [comment]
See https://github.com/couchbaselabs/sync-gateway-testcluster/pull/38
