### ISSUE TITLE
Pass $AWS_KEY as parameter to create_and_instantiate_cluster.py

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/sync-gateway-testcluster#4]
The motive behind this is to make this less "sticky".  Eg, the user should be aware of what AWS key they are using when they spin up clusters, rather than accidentally spinning them up under the wrong key.

**Comment by tleyden** [comment]
I made one small improvement to detect if $AWS_KEY was not set and throw an error.

**Comment by tleyden** [comment]
Yup
