### ISSUE TITLE
Alternate format for temp_ansible_hosts file

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/sync-gateway-testcluster#8]
I reworked the gateload config generator script, but it wants the ansible inventory file to be of this form:

```
[couchbase_servers]
ec2-54-205-165-155.compute-1.amazonaws.com

[sync_gateways]
ec2-54-158-112-128.compute-1.amazonaws.com

[load_generators]
ec2-54-163-112-228.compute-1.amazonaws.com

```

rather than ..

```
cb1 ansible_ssh_host=ec2-54-205-165-155.compute-1.amazonaws.com
sg1 ansible_ssh_host=ec2-54-158-112-128.compute-1.amazonaws.com
lg1 ansible_ssh_host=ec2-54-163-112-228.compute-1.amazonaws.com

[couchbase_servers]
cb1

[sync_gateways]
sg1

[load_generators]
lg1
```

Can you try changing the temp_ansible_hosts to:

```
[couchbase_servers]
cb1 ansible_ssh_host=172.23.105.164

[sync_gateways]
sg1 ansible_ssh_host=172.23.105.165
```

and if everything works, then change the conf/ini_to_ansible_host.py to output in that form?

That way, it will be closer to the temp_ansible_hosts that will be used for the AWS stuff (which will be generated from AWS when https://github.com/couchbaselabs/sync-gateway-testcluster/issues/7 is done -- initially the ticket was to generate a conf/hosts.ini, but I think it makes sense to skip that and jump straight to generating temp_ansible_hosts)

By the way, is conf/hosts.ini still used directly anywhere?

**Comment by tleyden** [comment]
I should say, the original problem is this.  Running the generate_gateload_configs.py script ends up running this ansible command

```
ansible load_generators --list-hosts -i ../temp_ansible_hosts
```

Which was returning `lg1` rather than the actual routable public ip.  Using the alternate format of temp_ansible_hosts fixes the issue.

**Comment by tleyden** [comment]
But, I just found out that alternate format causes an issue:

```
PLAY [couchbase_servers] ******************************************************

GATHERING FACTS ***************************************************************
ok: [ec2-54-205-165-155.compute-1.amazonaws.com]

TASK: [debug msg="Couchbase server primary node {{ couchbase_server_primary_node }}"] ***
fatal: [ec2-54-205-165-155.compute-1.amazonaws.com] => host not found: cb1
```

**Comment by sethrosetter** [comment]
that is because of this https://github.com/couchbaselabs/sync-gateway-testcluster/blob/master/provision/ansible/playbooks/install-couchbase-server-package.yml#L17

**Comment by tleyden** [comment]
@ajres I know you did some pretty [fancy stuf](https://github.com/couchbaselabs/perfcluster-aws/blob/master/ansible/playbooks/configure-gatling.yml#L52-L56) for the gatling config -- do you know how to get the first host from a named ansible group?

**Comment by ajres** [comment]
This is one option, there may be a better/simpler one.

Note that this example is able to select hosts not in the current working set, so you can pick an SG host while running an ansible playbook on a gateload host

Just change groups.tag_Type_syncgateway to whatever tagged group you want to select from

Change ec2_private_ip_address to whatever inventory property you want to retrieve from the host

---
- hosts: 127.0.0.1
  connection: local

  tasks:

  - name: Display first host from tag group
    debug: var=hostvars[groups.tag_Type_syncgateway[0]].ec2_private_ip_address

**Comment by tleyden** [comment]
Ok I think we'd want hostvars[groups.sync_gateways[0]].ansible_ssh_host

**Comment by tleyden** [comment]
I managed to remove all the hardcoded `cb1` references and replaced them with `couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].inventory_hostname }}"`  Cheers @ajres!

**Comment by tleyden** [comment]
The temp_ansible_hosts for the AWS and VM stuff are now in-line.. there are some minor cosmetic differences but they don't matter at all.
